require_relative '../node_modules/react-native/scripts/react_native_pods'
                  require_relative '../node_modules/react-native-permissions/scripts/setup'

                  workspace 'ContinentalAssitApp.xcworkspace'
                  platform :ios, min_ios_version_supported
                  prepare_react_native_project!

                  install! 'cocoapods', :deterministic_uuids => false

                  setup_permissions([
                    'LocationAccuracy',
                    'LocationAlways',
                    'LocationWhenInUse',
                  ])

                  target 'ContinentalAssitApp' do
                    config = use_native_modules!

                    use_react_native!(
                      :path => config[:reactNativePath],
                      :app_path => "#{Pod::Config.instance.installation_root}/.."
                    )

                    target 'ContinentalAssitAppTests' do
                      inherit! :complete
                    end

                    post_install do |installer|
                      # Aplicar configuraciones para solucionar el error std::char_traits<unsigned char>
                      installer.pods_project.targets.each do |target|
                        target.build_configurations.each do |config|
                          # Asegurar que GCC_PREPROCESSOR_DEFINITIONS sea un array
                          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']

                          # Añadir definiciones para arreglar el problema de char_traits
                          fixes = [
                            '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION',
                            '_LIBCPP_DISABLE_AVAILABILITY',
                            '_LIBCPP_ENABLE_CXX20_REMOVED_FEATURES'
                          ]

                          fixes.each do |fix|
                            unless config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?(fix)
                              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << fix
                            end
                          end

                          # Configurar C++20 para compatibilidad con iOS 18.4
                          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
                        end
                      end

                      # Aplicar configuración estándar de React Native
                      react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
                    end
                  end