	// Generated by https://quicktype.io

	export interface ActualizarSession {
		resultado: Resultado;
		cantidad:  number;
		error:     boolean;
	}

	export interface Resultado {
		usuario: 				UsuarioActualizarSession[];
		ordenes_registradas: null;
		beneficiarios:       any[];
	}

	export interface UsuarioActualizarSession {
		id_usuario:          string;
		email:               string;
		nombre:              string;
		nacimiento:          string;
		password:            string;
		status:              string;
		codigo_registro:     string;
		fecha_registro:      string;
		avatar:              null;
		pais_name:           string;
		telefono:            string;
		pais_flag:           string;
		pais_callingCode:    string;
		numero_beneficiario: number;
		telefonos:           TelefonoActualizarSession[];
	}

	export interface TelefonoActualizarSession {
		id:               string;
		id_usuario:       string;
		pais_name:        string;
		pais_callingCode: string;
		telefono:         string;
		pais_flag:        string;
	}
