// Generated by https://quicktype.io

export interface BeneficiosRespuesta {
  resultado: Beneficios[];
  cantidad: number;
  error: boolean;
  tipos_beneficios: TiposBeneficio[];
}

export interface Beneficios {
  idbeneficio: string;
  nombre: string;
  cobertura: string;
  idfamilia: string;
  descripcion: string;
}

export interface TiposBeneficio {
  id: string;
  id_tipo_beneficio: string;
  nombre: string;
  icono_tipo_beneficio: string;
  lenguaje: string;
}
