// Generated by https://quicktype.io

export interface BeneficiosRespuesta {
	resultado:        Beneficios[];
	cantidad:         number;
	error:            boolean;
	tipos_beneficios: TiposBeneficio[];
}

export interface Beneficios {
	id_beneficio:      number;
	nombre:            string;
	valor:             string;
	id_tipo_beneficio: number;
	descripcion:       string;
}

export interface TiposBeneficio {
	id:                    number;
	id_tipo_beneficio:     number;
	nombre_tipo_beneficio: string;
	icono_tipo_beneficio:  string;
	lenguaje:              string;
}
