// Generated by https://quicktype.io

export interface ConsultasPreguntasFrecuentes {
    resultado: PreguntasFrecuentes[];
    cantidad:  number;
    error:     boolean;
}

export interface PreguntasFrecuentes {
    id_pregunta_frecuente: number;
    id_orden:              number;
    pregunta:              string;
    respuesta:             string;
    lenguaje:              string;
}


