// Generated by https://quicktype.io

export interface ConsultaRegistro {
    resultado: Registro[];
    cantidad:  number;
    error:     boolean;
}

export interface Registro {
    id:              string;
    id_emision:      null;
    codigo:          string;
    fecha:           string;
    nombre_contacto: string;
    salida:          string;
    retorno:         string;
    origen:          string;
    destino:         string;
    plan:            string;
    categoria:       string;
    cantidad:        string;
    beneficiarios:   Beneficiario[];
}

export interface Beneficiario {
    id:                  string;
    nombre:              string;
    apellido:            string;
    email:               string;
    telefono:            string;
    nacimiento:          string;
    edad:                string;
    documento:           string;
    voucherBeneficiario: string;
}
