// Generated by https://quicktype.io

export interface ListaTelefonos {
	resultado: Telefonos[];
	cantidad:  number;
	error:     boolean;
}

export interface Telefonos {
	pais:       string;
	numero:     string;
	alpha2code: string;
	callingCodes: string;
}
