// Generated by https://quicktype.io

export interface Data {
	resultado: Resultado;
	cantidad:  number;
	error:     boolean;
}


export interface Resultado {
	usuario:             Usuario;
	ordenes_registradas: null;
	beneficiarios:       any[];
}


export interface Usuario {
	id_usuario: string;
	nombre:     string;
	nacimiento: string;
	email:      string;
	avatar:     null;
	telefonos:  Telefono[];
}

export interface Telefono {
	id:               string;
	id_usuario:       string;
	pais_name:        string;
	pais_callingCode: string;
	telefono:         string;
	pais_flag:        string;
}

