// Generated by https://quicktype.io

export interface Data {
	resultado: LoginRespuesta | ErrorUsuarioLogin[];
	cantidad:  number;
	error:     boolean;
}


export interface LoginRespuesta {
	usuario: UsuarioLogin;
	ordenes_registradas: null;
	beneficiarios:       any[];
}


export interface UsuarioLogin {
	id_usuario: string;
	nombre:     string;
	nacimiento: string;
	email:      string;
	avatar:     null;
	telefonos:  Telefono[];
}

export interface Telefono {
	id:               string;
	id_usuario:       string;
	pais_name:        string;
	pais_callingCode: string;
	telefono:         string;
	pais_flag:        string;
}

export interface ErrorUsuarioLogin {
    mensaje_error: string;
}



export interface TelefonosRespuesta {
	resultado: RespuestaTelefonos[];
	cantidad:  number;
	error:     boolean;
}

export interface RespuestaTelefonos {
	id:               string;
	id_usuario:       string;
	pais_name:        string;
	pais_callingCode: string;
	telefono:         string;
	pais_flag:        string;
}