// Generated by https://quicktype.io

export interface ConsultaMotivosReembolsos {
    resultado: MotivosReembolsos[];
    cantidad:  number;
    error:     boolean;
}

export interface MotivosReembolsos {
    id_motivo_reembolso: string;
    nombre_motivo:       string;
}
